---
development:
  cloud_name: dvrazopaf
  api_key: '485511223674612'
  api_secret: 4x_saKIVXDRnnPxXSZZoDIgo9Sg
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dvrazopaf
  api_key: '485511223674612'
  api_secret: 4x_saKIVXDRnnPxXSZZoDIgo9Sg
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dvrazopaf
  api_key: '485511223674612'
  api_secret: 4x_saKIVXDRnnPxXSZZoDIgo9Sg
  enhance_image_tag: true
  static_file_support: false
